name:                parallel-mvc
version:             0.1.0.0
github:              "tony-feasts/parallel-mvc"

extra-source-files:
  - README.md

description:         Please see the README on GitHub

dependencies:
  - base >= 4.7 && < 5
  - vector
  - random
  - bytestring
  - containers
  - monad-par
  - parallel

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-export-lists
  - -Wmissing-home-modules
  - -Wpartial-fields
  - -Wredundant-constraints

library:
  source-dirs: src

executables:
  graph-generator:
    main: graph-generator/Main.hs
    source-dirs: app
    dependencies: [parallel-mvc]
  mvc:
    main: mvc/Main.hs
    source-dirs: app
    dependencies: [parallel-mvc]
    ghc-options:
      - -threaded
      - -rtsopts
      - -O2

tests:
  pv1:
    main: pv1.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -O2
    dependencies: [parallel-mvc]
  pv2:
    main: pv2.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -O2
    dependencies: [parallel-mvc]
  pv3:
    main: pv3.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -O2
    dependencies: [parallel-mvc]
  pv4:
    main: pv4.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -O2
    dependencies: [parallel-mvc]
  sv1:
    main: sv1.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -O2
    dependencies: [parallel-mvc]
  sv2:
    main: sv2.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -O2
    dependencies: [parallel-mvc]
